trigger: none
pr: none

variables:
  buildConfiguration: 'Release'

jobs:
# ==============================================================================
# Ubuntu 24.04 Test
# ==============================================================================
- job:

  pool:
    name: Default

    
  steps:
  - checkout: self
    clean: true

  - powershell: |
      Write-Host "Listing global.json files under DemoAPI..."
      Get-ChildItem -Path "$(Build.SourcesDirectory)\DemoAPI" -Recurse -Filter global.json | ForEach-Object {
      Write-Host "---- $($_.FullName) ----"
      Get-Content $_.FullName
      }
    displayName: "Dump global.json contents"

  - script: echo DotNetVersion=$(DotNetVersion)
    displayName: Debug DotNetVersion variable
  
  
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore (DemoAPI)"
    inputs:
      command: "restore"
      workingDirectory: "MSTest"

  - script: |
      dotnet --info
      dotnet --version
    displayName: 'Verify .NET SDK version'

  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: "test"
      projects: "MSTest/MSTest.csproj"
      workingDirectory: "MSTest"
      publishTestResults: false



